.TH check_modbus 1 "Sep 2015" ""   ""
.SH NAME
check_modbus - tool to monitor state of different devices in Nagios using Modbus-TCP/RTU protocols.

.SH SYNOPSIS
.TP
\fBcheck_modbus\fR [ options ] [ \-\-ip= | \-H ] hostname \-f function 
.TP
\fBcheck_modbus\fR [ options ] [ \-\-serial= | \-S ] serial_port \-f function
.TP
\fBcheck_modbus\fR [ options ] \-\-file filename \-f function
.SH DESCRIPTION
.SS Dump mode
 Dump mode allows to save up to 127 16-bit registers as a binary file and process this file later using \fBcheck_modbus\fR or any other program.
 It can used in following cases:
.RS
.TP
- slave device can not handle several TCP/IP connections,
.TP
- slave device use RS232/RS485 interface.  Therefore only one connection is allowed,
.TP
- slave devices uses non-standard data format.
.RE
.TP
Firstly the binary dump file should be created. To avoid read/write concurrency is recommended to use lock files (see options \fB--lock_file_in\fR and \fB--lock_file_out\fR).
.RS
.TP
check_modbus --ip=plc01 -a 1 -f 4 --dump --dump_format 1 --dump_size 60 > file.dump
.RE
.RS
check_modbus --ip=plc01 -a 1 -f 4 --dump --dump_format 1 --dump_size 60 --dump_file file.dump
.RE
.TP


.TP
Afterwards many parameters can be analyzed from created dump file. 
.RS
.TP
.PD 0
check_modbus --file=file.dump -F 7 -f 4 -a 20 -w 100 -c 150
.TP
check_modbus --file=file.dump -F 7 -f 4 -a 18 -w 100 -c 150
.TP
check_modbus --file=file.dump -F 7 -f 4 -a 16 -w 100 -c 150
.TP
check_modbus --file=file.dump -F 1 -f 4 -a 1  -w 100 -c 150
.TP
check_modbus --file=file.dump -F 2 -f 4 -a 2  -w 100 -c 150
.RE
.PD
.TP
Only \fBbinary\fR dump format can by used as an input source for \fBcheck_modbus\fR. Other formats (hexadecimal and decimal) may be useful for other programs. 
.SH OPTIONS
.TP
\fB \-v, \-\-verbose\fR
turn on verbose mode. Additional debug information (settings, modbus debug ) will be printed 
.TP
.TP
\fB \-\-version\fR
display version information
.TP
\fB \-h, \-\-help\fR
print help for a command
.TP
\fB \-H, \-\-ip\fR=\fIHOSTNAME\fR
IP address or hostname. IPv6 address can be used here as well. 
.TP
\fB \-p, \-\-port\fR=\fIPORT\fR
TCP port number used for Modbus-TCP. By default is 502.
.TP
\fB \-S, \-\-serial\fR=\fISERIAL_DEVICE\fR
Serial port to use
.TP
\fB \-b, \-\-serial_bps\fR=\fI=SPEED\fR
Serial port speed. Default is 9600 bps.
.TP
\fB \-\-serial_mode\fR=\fIMODE\fR
RS mode of serial port. Default is 0.
.RS
.PD 0
.TP
0
-
RS232
.TP
1
-
RS485
.RE
.PD
.TP
\fB \-\-serial_parity\fR=\fIPARITY\fR
Serial port parity settings. Default none. Allowed values: none/N, even/E, odd/O
.TP
\fB \-\-serial_data_bits\fR=\fIDATA_BITS\fR
Serial port number of data bits. Default 8. Allowed values: 5, 6, 7, 8.
.TP
\fB \-\-serial_stop_bits\fR=\fISTOP_BITS\fR
Serial port number of stop bits. Default 1. Allowed values: 1, 2
.TP
\fB \-\-file\fR=\fIFILE\fR
Use binary input file as a source for data instead of communicating with device using TCP/IP or serial ports.
.TP
\fB \-d, \-\-device\fR=\fINUMBER\fR
Device modbus number. Default 1
.TP
\fB \-a, \-\-adress\fR=\fINUMBER\fR
Register or bit address. Can be hexadecimal (-a 0x0F) , octal (-a 017) or
decimal (-a 15). Default 1

Sometimes device's modbus registers
description starts from 0 address,
sometimes from 1. The least address in check_modbus is 1. So if in
device's registers start from 0, increment register address to set
correct value to -a parameter.
.TP
\fB \-t, \-\-try\fR=\fINUMBER\fR
Number of tries to connect modbus device. It's useful to get reliable answer from the device in noisy environment. Default 1.
.TP
\fB \-F, \-\-format\fR=\fIFORMAT\fR
Data format. Default 1 (signed word)
.RS
.PD 0
.TP 
1
- int16_t
.TP
2
- uint16_t
.TP
3
- int32_t
.TP
4
- uint32_t
.TP
5
- int64_t
.TP
6
- uint64_t
.TP
7
- float
.TP
8
- double
.PD
.RE
.TP
\fB \-s, \-\-swapbytes\fR
Swap bytes in each incomming word
.TP
\fB \-i, \-\-inverse\fR
Inverse order of \fBwords\fR in the packet. To convert data from big-endian to little-endian or the other way use both options \fB-i\fR and \fB-s\fR at the same time.
.TP
\fB \-f, \-\-function\fR=\fIFUNCTION\fR
Used modbus function. 
.RS
.PD 0
.TP
1
- Read coils
.TP
2
- Read input discretes
.TP
3
- Read holding registers
.TP
4
- Read input registers
.PD
.RE
.TP
\fB \-n, \-\-null\fR
If the query will get zero, program returns the critical signal
.TP
\fB \-N, \-\-not_null\fR
If the query will get non-zero valur, program returns the critical signal
.TP
\fB \-w, \-\-warning\fR=\fIRANGE\fR
Warning range. (see "Threshold and ranges" in Nagios documentation).
.TP
\fB \-c, \-\-critical\fR=\fIRANGE\fR
Critical range. Format is the same as for warning range.

.TP
\fB \-m, \-\-perf_min\fR=\fINUMBER\fR
Minimum value for performance data
.TP
\fB \-M, \-\-perf_max\fR=\fINUMBER\fR
Maximum value for performance data
.TP
\fB \-P, \-\-perf_data\fR
Enable showing performance data. By default performance data is disabled
.TP
\fB \-L, \-\-perf_label\fR=\fILABEL_STRING\fR
Label for performance data
.TP
\fB \-\-dump\fR
Dump incomming registers and bits to stdout instead of analyze their values. Dump mode disables showing performances data as well as critical/warning signalization.
.TP
\fB \-\-dump_format\fR=\fIDUMP_FORMAT\fR
Format of output dump. Default 1 (binary).
.RS
.PD 0
.TP
1
- binary
.TP
2
- hexadecimal
.TP
3
- decimal
.PD
.RE

.TP
\fB \-\-dump_size\fR=\fINUMBER\fR
Number of registers (2 bytes) or bits in output dump. The dump starts
from address given by parameter \fB\-a, \-\-address\fR.
.TP 
\fB \-\-dump_file\fR=\fIFILE\fR
Save dump to the file. If no dump file was specified in the dump mode,
then stdout will be used for output.
.TP
\fB \-\-lock_file_in\fR=\fIFILE\fR
Name of lock file used with input source. If the specified lock file
exists and process created it is still running, input source will not be
opened. This lock file is useful if several checks may access  input
source at the same time, but the source does not support this. For
example, serial ports can be opened by several programs simultaneously, some simple Ethernet devices can't handle
more than one request at the same time or by using dump file as input
source may exist concurrency between read and write process (see
\fB\-\-lock_file_out\fR).
.TP
\fB \-\-lock_file_out\fR=\fIFILE\fR
Name of lock file used by creating output dump file.
.TP
\fB \-\-gain\fR=\fIFLOAT\fR
Gain value. The read value can be adjusted using expression gain*value+offset (see
\fB\-\-offset\fR). This can be used to convert values with fixed
floating point to floating point format.
.TP
\fB \-\-offset\fR=\fIFLOAT\fR
Offset value. (for details see \fB\-\-gain\fR description)

.SH EXIT STATUS
Program can return the following codes:
.TP
0
- value is OK
.TP
1
- warning level
.TP
2
- critical level
.TP
3 
- general error
.TP
4
- unknown error
.TP
5 
- help information were returned
.TP
6
- wrong arguments
.TP
7
- connection error
.TP
8
- read error
.TP
9 
- unsupported function
.TP
10
- unsupported format

.SH EXAMPLES
.TP
check_modbus --ip=192.168.1.123 -a 13 -f 4 -F 7 -w 10:123.4 -c -20:234.5
read float value from modbus address 13 using Modbus-TCP
.TP
check_modbus --ip=192.168.1.123 -a 15 -f 4 -w ~:2345 -c ~:1234
read signed integer value from modbus address 15
.TP
check_modbus --ip=plc01 --try=5 -d 2 -a 20 -f 2 -n 
.TP
check_modbus --ip=plc01 -a 1 -f 4 --dump --dump_format 1 --dump_size 60 --dump_file file.dump
save 60 registers from plc01 to the file.dump in binary format. All these registers can be analyzed later off-line or even on the other machine. See next example.
.TP
check_modbus --file=file.dump -F 7 -f 4 -a 20 -c @30:150
Off-line analization of data from a dump file.
.TP
check_modbus --serial=/dev/ttyS0 -d 2 -a 7 -f 4 -n
.SH AUTHORS
.PD 0
.TP
Andrey Skvortsov <Andrej.Skvortzov@gmail.com>
.TP
Mirosław Lach    <m.github@lach.waw.pl>
.SH NOTES
Since version 0.47 is changed behavior for options -w and -c to be
compliant with standard Nagios ranges format.

All bug reports can be posted on the GitHub page https://github.com/AndreySV/check_modbus
.SH COPYRIGHT
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
.br
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
